colors=["red","blue","black","orange","magenta","brown","gray","green","pink","violet","gold","turquoise"]
widths=[1,2,3,4,5]
styles=["-","--",":","-.","-",""]
markers=["",".","o","s","^","d","p","*","x","+"]
alpha=[1.00,0.75,0.50]
